update German language for ver1.17
Prospector/ModMenu pull request #283
Opened 2021-07-11 00:07 UTC by CC044

updated German language for ver1.17

2021-07-13 09:33 UTC, jackassmc requested changes

2021-07-13 09:33 UTC, jackassmc commented on src/main/resources/assets/modmenu/lang/de_de.json
> +  "modmenu.minecraft": "Minecraft",
Please remove all entries that aren't changed.

2021-07-13 09:33 UTC, jackassmc commented on src/main/resources/assets/modmenu/lang/de_de.json
> +  "option.modmenu.mod_count_location.mods_button": "Mods Schalter",
Is `Button` commonly localized in German?

2021-07-13 09:33 UTC, jackassmc commented on src/main/resources/assets/modmenu/lang/de_de.json
> +  "option.modmenu.mods_button_style.classic": "Below Realms",
Missing translation.

2021-07-13 09:33 UTC, jackassmc commented on src/main/resources/assets/modmenu/lang/de_de.json
> +  "option.modmenu.mods_button_style.shrink": "Adjacent",
Missing translation.

2021-07-14 05:23 UTC, CC044 commented on src/main/resources/assets/modmenu/lang/de_de.json
> +  "modmenu.minecraft": "Minecraft",
I have removed everything that is the same as in en_us.json file.

2021-07-14 11:53 UTC, jackassmc requested changes
Please test your changes. To do this you can add the new localization file to the Mod Menu JAR file or compile Mod Menu yourself (there are currently problems with the Terraformers Maven so this is more complicated than usual).

There are two problems:
- Many texts are wider than the buttons
- `: ` is displayed twice (it gets added automatically)

It might be acceptable to just not translate `Button`? Or maybe there is a shorter localized alternative?

2021-07-30 10:20 UTC, closed without merging