Fix: Only add 'v' to version if the mod has not done so itself
Prospector/ModMenu pull request #316
Opened 2021-08-25 14:14 UTC by spnda

ModMenu was always just adding a "v" character in front of the version string. Funnily enough, ModMenu itself already adds a 'v' to its version so it's effectively doubled. See the screenshot below of how it used to look:
![image](https://user-images.githubusercontent.com/43609023/130806758-0e3f363f-87a7-4807-ac1e-5a3d6f2820d5.png)

2021-08-25 14:42 UTC, RDKRACZ commented
![Screenshot from 2021-08-25 16-40-49](https://user-images.githubusercontent.com/43277609/130811514-ab65eea1-a61b-424f-a726-781f30d7cb7a.png)
Tried 2.0.4 and 2.0.5 and they don't have doubled "v". Isn't this because you are not on the official release? (I'm guessing this from the "+feat/update-checker" thing)

2021-08-25 14:52 UTC, spnda commented
Oh true. It seems that the additional `v` is generated from the `getVersion` gradle function when using development builds: https://github.com/TerraformersMC/GradleScripts/blob/6c0b2fdd3ba732b3cf521a3b0cec135eb8b7094a/ferry.gradle#L278-L306

However, I still think it's a valid issue as other mod authors might add it without thinking about it.

2021-08-25 16:39 UTC, haykam821 requested changes
This is a good idea. I think it could potentially also collapse other prefixes such as `ver` or `version` plus any remaining whitespace.

2021-08-25 16:39 UTC, haykam821 commented on src/main/java/com/terraformersmc/modmenu/gui/ModsScreen.java
> +				if (!versionString.startsWith("v")) versionString = "v" + versionString;
I would move this to an internal helper.

2021-08-25 17:45 UTC, spnda commented on src/main/java/com/terraformersmc/modmenu/gui/ModsScreen.java
> +				if (!versionString.startsWith("v")) versionString = "v" + versionString;
As there is no existing `StringUtil` or `VersionUtil` class, would you think that just creating a `StringUtil` class with a `sanitizeVersion` function that just removes `v` and `ver` from the String would be a good solution?

2021-08-26 14:12 UTC, jackassmc commented
Please move this into the `Mod` interface and change it to return the prefixed version from there.
Then also backport this to 1.16.

2021-08-26 14:24 UTC, spnda commented
> Please move this into the `Mod` interface and change it to return the prefixed version from there.
> Then also backport this to 1.16.

So you are suggesting a `default` interface function that would take the value of `getVersion`, sanitize it, add the `'v'` and return that? So something like this?
```java
default String getSanitizedVersion() {
    String version = getVersion();
    if (version.startsWith("v")) version = version.substring(1);
    return version;
}
```

2021-08-26 14:34 UTC, jackassmc commented
No, add `getPrefixedVersion` to `FabricMod` and take care of everything there, ie. check if there is already a prefix and if so correct it or if not add it. Also don't use single line if statements.

2021-08-26 15:21 UTC, spnda commented
Ok, I've however added it to the `Mod` interface, as in both use cases we only have `Mod`, not `FabricMod`.

2021-08-26 16:18 UTC, jackassmc commented
The reason it should go in `FabricMod` is because `DummyMod` doesn't have a version, it's just an empty string and the prefixed version would just be `"v"`.
Also look at the `Mod` interface, it's an actual interface, there's only function signatures, no function bodies. You should try to follow the style of the surrounding code.

So:
- Add the `getPrefixedVersion` signature to the `Mod` interface
- Implement it to handle leading whitespace and existing `v`, `ver` and `version` prefixes in `FabricMod`
- Implement it to return an empty string in `DummyMod`
- Do the same thing on the 1.16 branch

2021-08-26 16:22 UTC, spnda commented
Sorry I misunderstood you at first. I didn't see the FabricDummyParentMod existed at all, so I just thought defaulting the function would be good enough, as realistically it's behavior one doesn't need to change often. And I'll cherry-pick the commit onto the 1.16 branch as soon as this is merged.

2021-08-26 16:28 UTC, jackassmc commented
The latest version is fine, you can go ahead an port it now.

2021-08-26 17:46 UTC, merged

2021-08-26 17:46 UTC, jackassmc commented
Thanks!