Generate more pleasant colors for the built in "java" mod
Prospector/ModMenu pull request #517
Opened 2022-12-29 12:21 UTC by Jab125

- Generate more pleasant colors for the built in "java" mod

2023-01-19 05:21 UTC, Prospector requested changes
I approve of this feature, but the implementation shouldn't use java.awt

2023-01-19 05:21 UTC, Prospector commented on src/main/java/com/terraformersmc/modmenu/util/DrawingUtil.java
> +import java.awt.*;
Can't use the java.awt Color class because it won't work on some systems like macOS iirc

2023-01-19 10:27 UTC, Jab125 commented on src/main/java/com/terraformersmc/modmenu/util/DrawingUtil.java
> +import java.awt.*;
i use the `Color` class all the time and it never caused any issues for me

2023-01-19 10:27 UTC, Jab125 commented on src/main/java/com/terraformersmc/modmenu/util/DrawingUtil.java
> +import java.awt.*;
i made this entire pull request on macos

2023-01-19 16:02 UTC, Prospector commented on src/main/java/com/terraformersmc/modmenu/util/DrawingUtil.java
> +import java.awt.*;
Apparently this hasn't been an issue since 1.18, I guess it's fine then.

2023-01-19 16:21 UTC, haykam821 commented on src/main/java/com/terraformersmc/modmenu/util/DrawingUtil.java
> +import java.awt.*;
The `MathHelper.hsvToRgb` method could be used instead.

2023-01-31 04:24 UTC, Prospector commented on src/main/java/com/terraformersmc/modmenu/util/DrawingUtil.java
> +import java.awt.*;
Oh cool, yeah makes sense to use the builtin Minecraft method then

2023-01-31 05:16 UTC, Prospector commented
Will merge in #529

2023-01-31 05:16 UTC, closed without merging