Update for 1.21 Pre 1
Prospector/ModMenu pull request #734
Opened 2024-05-29 16:23 UTC by sakura-ryoko

Rendering and Identifier fixes primarily.

2024-05-29 16:24 UTC, sakura-ryoko commented
I commonly need to update Mod Menu myself for downstream mod development...  So I decided to give back my work this time.

2024-05-29 16:32 UTC, Prospector commented on src/main/java/com/terraformersmc/modmenu/gui/ModMenuOptionsScreen.java
> +		ModMenuConfigManager.save();
is there a reason for making it save configs after checking for updates? curious why you changed this

2024-05-29 16:33 UTC, sakura-ryoko commented on src/main/java/com/terraformersmc/modmenu/gui/ModMenuOptionsScreen.java
> +		ModMenuConfigManager.save();
You can revert this I was unsure which branch was the correct from 1.20.3 or 1.20.5, they are different.

2024-05-29 16:33 UTC, Prospector commented on src/main/java/com/terraformersmc/modmenu/gui/ModMenuOptionsScreen.java
> +		ModMenuConfigManager.save();
I see, I don't think it matters was just wondering why it was changed

2024-05-29 16:35 UTC, LostLuma commented on src/main/java/com/terraformersmc/modmenu/gui/ModMenuOptionsScreen.java
> +		ModMenuConfigManager.save();
It's probably better to save the config first since the user may have changed what type of updates they want to see.

2024-05-29 16:35 UTC, Prospector requested changes

2024-05-29 16:35 UTC, Prospector commented on src/main/java/com/terraformersmc/modmenu/gui/widget/entries/ModListEntry.java
> +	private static final Identifier MOD_CONFIGURATION_ICON = Identifier.of("modmenu", "textures/gui/mod_configuration.png");
these should probably use the namespace reference in the ModMenu class

2024-05-29 16:35 UTC, Prospector commented on src/main/java/com/terraformersmc/modmenu/gui/widget/entries/ModListEntry.java
> +	private static final Identifier ERROR_HIGHLIGHTED_ICON = Identifier.of("minecraft", "world_list/error_highlighted");
minecraft namespace can be omitted

2024-05-29 16:36 UTC, Prospector commented on src/main/java/com/terraformersmc/modmenu/gui/ModMenuOptionsScreen.java
> +		ModMenuConfigManager.save();
ah yes, that makes sense

2024-05-29 16:38 UTC, sakura-ryoko commented on src/main/java/com/terraformersmc/modmenu/gui/widget/entries/ModListEntry.java
> +	private static final Identifier MOD_CONFIGURATION_ICON = Identifier.of("modmenu", "textures/gui/mod_configuration.png");
Okay, I didn't change that, it's how it was in the original code.

2024-05-29 16:46 UTC, sakura-ryoko commented
Changes made

2024-05-29 16:52 UTC, Prospector commented on src/main/java/com/terraformersmc/modmenu/gui/widget/entries/ModListEntry.java
> +	private static final Identifier MOD_CONFIGURATION_ICON = Identifier.of("modmenu", "textures/gui/mod_configuration.png");
ah I see, that's weird

2024-05-30 15:45 UTC, sakura-ryoko commented on src/main/java/com/terraformersmc/modmenu/gui/widget/entries/ModListEntry.java
> +	private static final Identifier ERROR_HIGHLIGHTED_ICON = Identifier.of("minecraft", "world_list/error_highlighted");
Was fixed, btw

2024-06-01 21:25 UTC, haykam821 requested changes
The port looks good overall to me. Could these smaller stylistic and method details be changed?

2024-06-01 21:25 UTC, haykam821 commented on src/main/java/com/terraformersmc/modmenu/gui/widget/UpdateAvailableBadge.java
> +	private static final Identifier UPDATE_ICON = Identifier.of("icon/trial_available");
Could the `Identifier.ofVanilla` factory method be used instead? The `Identifier.of` method with a single parameter will try to parse `:` from a string, which isn't necessary in this case.

```suggestion
	private static final Identifier UPDATE_ICON = Identifier.ofVanilla("icon/trial_available");
```

2024-06-01 21:25 UTC, haykam821 commented on src/main/java/com/terraformersmc/modmenu/gui/widget/entries/ModListEntry.java
> +	private static final Identifier ERROR_HIGHLIGHTED_ICON = Identifier.of("world_list/error_highlighted");
```suggestion
	public static final Identifier UNKNOWN_ICON = Identifier.ofVanilla("textures/misc/unknown_pack.png");
	private static final Identifier MOD_CONFIGURATION_ICON = Identifier.of(ModMenu.MOD_ID, "textures/gui/mod_configuration.png");
	private static final Identifier ERROR_ICON = Identifier.ofVanilla("world_list/error");
	private static final Identifier ERROR_HIGHLIGHTED_ICON = Identifier.ofVanilla("world_list/error_highlighted");
```

2024-06-01 21:25 UTC, haykam821 commented on src/main/java/com/terraformersmc/modmenu/gui/widget/ModListWidget.java
> +					catch (Exception ignored) {}
Nitpick: braces should be on the same lines as keywords.

```suggestion
					try {
						builtBuffer = buffer.end();
						BufferRenderer.drawWithGlobalProgram(builtBuffer);
						builtBuffer.close();
					} catch (Exception e) {
						// Ignored
					}
```

2024-06-01 21:25 UTC, haykam821 commented on src/main/java/com/terraformersmc/modmenu/gui/widget/ModListWidget.java
> +					catch (Exception ignored) {}
Nitpick: braces should be on the same lines as keywords.

```suggestion
					try {
						builtBuffer = buffer.end();
						BufferRenderer.drawWithGlobalProgram(builtBuffer);
						builtBuffer.close();
					} catch (Exception e) {
						// Ignored
					}
```

2024-06-01 21:25 UTC, haykam821 commented on src/main/java/com/terraformersmc/modmenu/gui/widget/DescriptionListWidget.java
> +			catch (Exception ignored) { }
Nitpick: braces should be on the same lines as keywords.

```suggestion
			try {
				builtBuffer = bufferBuilder.end();
				BufferRenderer.drawWithGlobalProgram(builtBuffer);
				builtBuffer.close();
			} catch (Exception e) {
				// Ignored
			}
```

2024-06-01 21:25 UTC, haykam821 commented on src/main/java/com/terraformersmc/modmenu/gui/widget/DescriptionListWidget.java
> +		catch (Exception ignored) { }
Nitpick: braces should be on the same lines as keywords.

```suggestion
		try {
			builtBuffer = bufferBuilder.end();
			BufferRenderer.drawWithGlobalProgram(builtBuffer);
			builtBuffer.close();
		} catch (Exception e) {
			// Ignored
		}
```

2024-06-01 21:25 UTC, haykam821 commented on src/main/java/com/terraformersmc/modmenu/gui/ModMenuOptionsScreen.java
> +	{
Nitpick: braces should be on the same lines as keywords.

```suggestion
	protected void addOptions() {
```

2024-06-02 04:14 UTC, sakura-ryoko commented on src/main/java/com/terraformersmc/modmenu/gui/widget/UpdateAvailableBadge.java
> +	private static final Identifier UPDATE_ICON = Identifier.of("icon/trial_available");
I was loathe to use the `ofVanilla` because the fabric team changed this Yarn naming a few times now.

2024-06-02 04:18 UTC, sakura-ryoko commented
I was hesitant to make the Identifier.of changes because previously the Fabric team changed the Yarn mappings of those about 2 or 3 times.

Also, the coding style I have baked into my brain from coding for masa's mods for the last several months, so I had to bake in his coding style into my brain, and have my IDE setup as such.

2024-06-04 01:04 UTC, haykam821 approved these changes

2024-06-04 01:13 UTC, merged