`depends` -> `recommends`
Prospector/ModMenu pull request #83
Opened 2019-12-07 12:50 UTC by shedaniel

also changed my name in contributors for no reason.

2019-12-07 17:43 UTC, Sollace commented
No.

Use this.
```
  "depends": {
    "fabricloader": ">=0.6.1",
    "fabric-api-base": ">=0.1.0",
    "fabric-events-lifecycle-v0": ">=0.1.0",
    "fabric-resource-loader-v0": ">=0.1.0",
    "minecraft": ">=1.15-"
  }```

2019-12-07 18:33 UTC, modmuss50 requested changes

2019-12-07 18:33 UTC, modmuss50 commented on src/main/resources/fabric.mod.json
> +  "recommends": {
No, it needs to depend on the specfic module it uses.

2019-12-08 10:51 UTC, shedaniel commented
I don't think modmenu depends on `api-base` or the `event-lifecycle`, but I have resolved the issue. Please check it out.

2019-12-08 18:52 UTC, Sollace commented
> 
> 
> I don't think modmenu depends on `api-base` or the `event-lifecycle`, but I have resolved the issue. Please check it out.

I included api-base because I wasn't sure if it was needed or not. (it seems like everything requires that).

`event-lifecycle` was just because I assumed it's needed to the `initialize` entrypoint to work.

2019-12-08 18:53 UTC, Sollace commented
This is fixing #82 by the way. (you can close it if you merge this)

2019-12-14 21:18 UTC, Prospector commented
Implemented in dev

2019-12-14 21:18 UTC, closed without merging